import { ContextProvider } from "./context/ContextAPI";
import "./globals.css";




export const metadata = {
  title: "HAPPY - SHOPPING",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
